### ISSUE TITLE
Admin tool UI

### ISSUE THREAD

**Issue by airtonjr** [kotamine/AppRumen#1]
Create an AppRumen Admin account (some gmail address) and create an Admin tab containing the following items: Delete Item, Send a Message, Export Data, Word-Trend, Publish Admin Memo, Publish Editor's Pick. In the Admin tab, regular users will see the results of Word-Trend, Admin Memo, and Editor's Pick

- Delete: Admin person selects either Post, User, or Comment, according to which a searchable table shows up. Then the admin searches and selects the item to delete

- Admin message: Admin person selects either all users or a particular user (through some form of search), write a message, and send.

- Export Data: Admin person selects a mongo db collection and exports it to a CSV file

- Word-Trend: Admin person sees a list of most frequently appeared words in posts., remove "the" or "and" etc. from the list, and publishes a trending word memo

- Admin Memo: Admin person writes a memo and publishes. When no longer needed, Admin archives the memo. This needs a new mongodb collection, say mongo_memo

- Editor's Pick: This is similar to admin memo above, but this note highlights about a post or user selected by Admin. Admin selects a post or user (the text has a link to its detail page) and write his/her comments of recommendation

**Comment by kotamine** [comment]
mostly done. I will make a manual page shortly.
