### ISSUE TITLE
add notes below icons for like/ follow etc. for mobile users

### ISSUE THREAD

**Issue by kotamine** [kotamine/AppRumen#29]

**Comment by Johnathannault** [comment]
Added help text to mobile version.

**Comment by kotamine** [comment]
It doesn't change from Like to Unlike or Follow to Unfollow.  Maybe that's difficult to do in CSS.  Let me know if I should do that in the Shiny sever side. Now I have access to window size in Shiny server, I can make it conditional.  It is now stored in input$windowWidth.

**Comment by kotamine** [comment]
okay thanks!  I don't know how to read those, but thanks for checking.
