### ISSUE TITLE
modal css:  set some radius for round corners

### ISSUE THREAD

**Issue by kotamine** [kotamine/AppRumen#33]
modals are used in announcements

**Comment by kotamine** [comment]
Also, please make changes for the arrangement of arrows (next and back).  They don't show up correctly in small window size.

**Comment by airtonjr** [comment]
Solution for the corners: 

` .modal-header {
      background-color: #5B0013;
      COLOR: #fff;
      border-top-left-radius: 0.35em;
      border-top-right-radius: 0.35em;
      
    }
    
    
    
    .modal-footer {
      background-color: #5B0013;
      COLOR: #fff;
       
      border-bottom-left-radius: 0.35em;
      border-bottom-right-radius: 0.35em;
    }
    
    
    .modal-content {
      background-color: #fff;
      COLOR: black;
      border-top-left-radius: 0.36em;
      border-top-right-radius: 0.36em;
      border-bottom-left-radius: 0.36em;
      border-bottom-right-radius: 0.36em;
    } `

![cornerscapture](https://cloud.githubusercontent.com/assets/7409463/14085488/beba8cec-f4e5-11e5-9601-684f0c284e4a.PNG)

**Comment by kotamine** [comment]
Modal  close button next to the title should be  the same color as the text.

**Comment by airtonjr** [comment]
Solution: 

```
 .close {
    color: #fff; 
    opacity: 1;
}
```

**Comment by Johnathannault** [comment]
added the css
