### ISSUE TITLE
Check transitions

### ISSUE THREAD

**Issue by airtonjr** [kotamine/AppRumen#4]
Check transitions (redirection when user takes a certain action) if they are in place as expected and properly working

**Comment by kotamine** [comment]
Restore the navigation related to  bsCollapse().  
- The default panel to be set by, for example, bsCollapse(...,open=Posts,)  which opens  bsCollapsePanel(title=Posts,...).  
- Redirected navigation to be set by, for example,  updateCollapse(session, "collapseMain", open = "Posts")

**Comment by kotamine** [comment]
can we all check for bugs by clicking for various links/transitions?

**Comment by kotamine** [comment]
the basic links should be working.  sometimes it stops working and then starts working again after visiting different pages. I am not sure why that happens.
