### ISSUE TITLE
User profile picture/logo

### ISSUE THREAD

**Issue by kotamine** [kotamine/AppRumen#7]
Set up user picture (and default logo) in the Details of User tab. When the user edits, he/she should be able to upload an image, which must be processed to a small size and added to the mongo_user database as S4. The image is then processed (round shape etc) and shown in the user profile.

**Comment by kotamine** [comment]
let's try storing image in www/img  and store the image file name in mongo_user$picture. 
when the user is editing his/her profile, a button for uploading an image is needed.  
once we launch in shinyapps.io, let's see if that works.

**Comment by kotamine** [comment]
we need some processing of image when the user uploads it. Let's resize the image and crop into a square etc.  Let's try to have a rounded image next to the user name in the listing under People.

**Comment by airtonjr** [comment]
Kota, 

What do you think about this image below?

![kotaprofilecapture](https://cloud.githubusercontent.com/assets/7409463/13263990/c5c2d856-da31-11e5-82fc-621215c23808.PNG)

**Comment by kotamine** [comment]
awesome!

**Comment by kotamine** [comment]
Can you find a way to store an user-uploaded image in mongoDB?

**Comment by Johnathannault** [comment]
I successfully uploaded an image manually, and the current code can read the file.  I am working on the interface to upload and image.  Airton has discovered a way to combine the profile picture from google authentication, and when that is complete I can implement the rest of my profile image code.

**Comment by kotamine** [comment]
I didn't notice you uploaded an image manually. Was it through R code?  Or shell?  Please put the code in the archive folder. It might be useful sometime later.
