### ISSUE TITLE
Back button from Android or iPhone

### ISSUE THREAD

**Issue by kotamine** [kotamine/AppRumen#9]
This may not be easy, but I wonder if we can make the generic Back button in cell phone to "work" (going to the previous state) for our app.  

here is some resource: 
http://developer.android.com/design/patterns/navigation.html
http://stackoverflow.com/questions/32353680/how-to-access-browser-session-cookies-from-within-shiny-app  
www.computerworld.com/article/2971265/application-development/how-to-drive-a-web-browser-with-r-and-rselenium.html

**Comment by airtonjr** [comment]
IOS does not use back button. They use just the home button.

**Comment by kotamine** [comment]
when people open the app in Android, do you think they expect the back button to work inside the app?  Are they going to be annoyed if the back button refreshes the website or takes back to previous webpage ? 
Let me know if there is a way to make the back button work inside the app. If there is, I would like to know how long it would take to implement it.

**Comment by kotamine** [comment]
forget it
